#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v18
# autospec commit: f35655a
#
Name     : efl
Version  : 1.27.0
Release  : 50
URL      : https://download.enlightenment.org/rel/libs/efl/efl-1.27.0.tar.xz
Source0  : https://download.enlightenment.org/rel/libs/efl/efl-1.27.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause FTL GPL-2.0 LGPL-2.1 MIT Zlib
BuildRequires : SDL-dev
BuildRequires : SDL2-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : fribidi-dev
BuildRequires : gst-plugins-base-dev
BuildRequires : gstreamer-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXcursor-dev
BuildRequires : libXtst-dev
BuildRequires : libavif-dev
BuildRequires : libjpeg-turbo-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: nogif.patch

%description
The EFL Enlightenment-X Icon theme. Orig. Based on Rave-X, Mint-X, Elementary
and Faenza icon Themes.

%prep
%setup -q -n efl-1.27.0
cd %{_builddir}/efl-1.27.0
%patch -P 1 -p1
pushd ..
cp -a efl-1.27.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725325527
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dwl=true \
-Dopengl=full \
-Dembedded-lz4=false \
-Dnative-arch-optimization=false \
-Devas-loaders-disabler=json \
-Decore-imf-loaders-disabler=scim \
-Dglib=true \
-Dg-mainloop=true \
-Dbuild-tests=false \
-Dbuild-examples=false  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dwl=true \
-Dopengl=full \
-Dembedded-lz4=false \
-Dnative-arch-optimization=false \
-Devas-loaders-disabler=json \
-Decore-imf-loaders-disabler=scim \
-Dglib=true \
-Dg-mainloop=true \
-Dbuild-tests=false \
-Dbuild-examples=false  builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/efl
cp %{_builddir}/efl-%{version}/licenses/COPYING.ASL %{buildroot}/usr/share/package-licenses/efl/a8f3e29d5eab4420318de979754f5637d4bf2c3f || :
cp %{_builddir}/efl-%{version}/licenses/COPYING.BSD %{buildroot}/usr/share/package-licenses/efl/8183e75e4fcf4799d0e4fa51b74855edc5eb8b87 || :
cp %{_builddir}/efl-%{version}/licenses/COPYING.DNS %{buildroot}/usr/share/package-licenses/efl/e675839915861b98343bb1733e77f64fd8d9e319 || :
cp %{_builddir}/efl-%{version}/licenses/COPYING.FTL %{buildroot}/usr/share/package-licenses/efl/52f4f83b6ebd38db17371a09ffe90ce4594505a3 || :
cp %{_builddir}/efl-%{version}/licenses/COPYING.GPL %{buildroot}/usr/share/package-licenses/efl/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/efl-%{version}/licenses/COPYING.LGPL %{buildroot}/usr/share/package-licenses/efl/5d1a0e378eba39192d02bc872f727c2ee8a2f0b7 || :
cp %{_builddir}/efl-%{version}/licenses/COPYING.NGINX-MIT %{buildroot}/usr/share/package-licenses/efl/1a00a507fb89bb0018c092d6835077d541e76dc2 || :
cp %{_builddir}/efl-%{version}/licenses/COPYING.SMALL %{buildroot}/usr/share/package-licenses/efl/49d7220235cd5c5d99df26599117b80fb2930593 || :
cp %{_builddir}/efl-%{version}/src/static_libs/fnmatch/COPYRIGHT %{buildroot}/usr/share/package-licenses/efl/4808116261778b2137bb955568032cd684fb199b || :
cp %{_builddir}/efl-%{version}/src/static_libs/libdrm/LICENSE %{buildroot}/usr/share/package-licenses/efl/070d60bcc974c1527f5c4bc7688b0866c957202c || :
cp %{_builddir}/efl-%{version}/src/static_libs/libunibreak/LICENCE %{buildroot}/usr/share/package-licenses/efl/b732f65dd876b409a3078bcfa24998526322bb63 || :
cp %{_builddir}/efl-%{version}/src/static_libs/lz4/LICENSE %{buildroot}/usr/share/package-licenses/efl/01e23675a9596a3a4571d3ed84d102fb6cb68181 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
## install_append content
chmod -R -s %{buildroot}/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
